tasks: Test directory attachment
cockpit-project/cockpituous pull request #591
Opened 2024-03-08 06:04 UTC by martinpitt

This reproduces https://github.com/cockpit-project/bots/issues/6042

2024-03-08 06:17 UTC, martinpitt commented
OK, this [fails in exactly the same way](https://github.com/cockpit-project/cockpituous/actions/runs/8199436949/job/22424533628?pr=591) as in https://github.com/cockpit-project/bots/issues/6042 .

2024-03-08 06:34 UTC, martinpitt commented
https://github.com/cockpit-project/bots/pull/6043 landed and it's green now.

2024-03-11 10:08 UTC, allisonkarlitskaya requested changes

2024-03-11 10:51 UTC, allisonkarlitskaya approved these changes

2024-03-11 10:51 UTC, merged